// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyNdfRkbqsZlh7B6PLNO-plSxoJMakn6E',
    appId: '1:246359242461:web:e1fc136236b08d6e89cd34',
    messagingSenderId: '246359242461',
    projectId: 'liquorlocate-8020c',
    authDomain: 'liquorlocate-8020c.firebaseapp.com',
    storageBucket: 'liquorlocate-8020c.appspot.com',
    measurementId: 'G-PV1TNGX7L4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTD7X15X2HZWZiaMJbaXCv2qfkBHIo6WQ',
    appId: '1:246359242461:android:c0722adeb906fee789cd34',
    messagingSenderId: '246359242461',
    projectId: 'liquorlocate-8020c',
    storageBucket: 'liquorlocate-8020c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATPElYObb8jAgKkfdd4hTXuFeoQdCxpjY',
    appId: '1:246359242461:ios:4ecf193d2b48940a89cd34',
    messagingSenderId: '246359242461',
    projectId: 'liquorlocate-8020c',
    storageBucket: 'liquorlocate-8020c.appspot.com',
    iosBundleId: 'com.example.liquorLocate3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATPElYObb8jAgKkfdd4hTXuFeoQdCxpjY',
    appId: '1:246359242461:ios:4ecf193d2b48940a89cd34',
    messagingSenderId: '246359242461',
    projectId: 'liquorlocate-8020c',
    storageBucket: 'liquorlocate-8020c.appspot.com',
    iosBundleId: 'com.example.liquorLocate3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyNdfRkbqsZlh7B6PLNO-plSxoJMakn6E',
    appId: '1:246359242461:web:2a0cf01a6a86164389cd34',
    messagingSenderId: '246359242461',
    projectId: 'liquorlocate-8020c',
    authDomain: 'liquorlocate-8020c.firebaseapp.com',
    storageBucket: 'liquorlocate-8020c.appspot.com',
    measurementId: 'G-GBHDQ2VRQ3',
  );

}